apiVersion: apps/v1
kind: Deployment
metadata:
  name: mac-nginx-deployment
  labels:
    app: mac-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mac-nginx
  template:
    metadata:
      labels:
        app: mac-nginx
    spec:
      containers:
        - name: mac-nginx
          image: nginx:latest
          ports:
            - containerPort: 80
