apiVersion: v1
kind: Service
metadata:
  name: mac-nginx-service
spec:
  type: NodePort
  selector:
    app: mac-nginx
  ports:
    - protocol: TCP
      port: 80 # Port of service
      targetPort: 80 # Port of Pod
      snodePort: 30001 # Port of Node
      # Node -> Service -> Pod
      