apiVersion: v1
kind: Service
metadata:
  name: mac-nginx-service
spec:
  type: NodePort
  selector:
    app: mac-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001